title: MiCasa Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: 
baseurl: "/blog"
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

social:
   github: 
   twitter: 
   facebook: 
   email: 

segment_analytics: ""
